# Render.com deployment configuration
build:
  commands:
    - pip install -r requirements.txt

run:
  command: uvicorn main:app --host 0.0.0.0 --port $PORT

env:
  - key: PYTHON_VERSION
    value: 3.11.0
